apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    app: mysite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      name: mysite-pod
      labels:
        app: mysite
    spec:
      containers:
      - name: django
        image: ghcr.io/johngray-git/cis-92:milestone-7.1 
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m 
            memory: 512Mi
            ephemeral-storage: 10Mi
          limits:
            cpu: 250m 
            memory: 512Mi
            ephemeral-storage: 10Mi
        envFrom:
        - configMapRef:
            name: mysite-config
        - secretRef:
            name: mysite-secret