apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: secure-redirect
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-ing
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
    networking.gke.io/v1beta1.FrontendConfig: secure-redirect
spec:
  tls: 
  - hosts: 
    - "www.jhg-cis-92.cis-92.com"
    secretName: apps-cert-secret
  rules:
  - host: "www.jhg-cis-92.cis-92.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysite-svc
            port:
              number: 80


